### ISSUE TITLE
golangci-lint: enable more linters

### ISSUE THREAD

**Issue by CarlJi** [qiniu/reviewbot#116]

**Comment by CarlJi** [comment]
error occurred when enabling all linters

```bash
[runner] Panic: interfacer: package \"floy\" (isInitialPkg: true, needAnalyzeSource: true): runtime error: invalid memory address or nil pointer dereference: goroutine 44186 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func1()\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:108 +0x277\npanic({0x1051040?, 0x1bf3cf0?})\n\truntime/panic.go:770 +0x132\ngolang.org/x/tools/go/ssa/ssautil.AllFunctions.func1(0xc074429a00)\n\tgolang.org/x/tools@v0.18.0/go/ssa/ssautil/visit.go:61 +0xf6\ngolang.org/x/tools/go/ssa/ssautil.AllFunctions.func2({0x1425d18, 0xc0951f3db0})\n\tgolang.org/x/tools@v0.18.0/go/ssa/ssautil/visit.go:78 +0x94\ngolang.org/x/tools/go/ssa/ssautil.AllFunctions(0xc085f2f5f0)\n\tgolang.org/x/tools@v0.18.0/go/ssa/ssautil/visit.go:131 +0x2c2\nmvdan.cc/interfacer/check.(*Checker).Check(0xc010e199e0)\n\tmvdan.cc/interfacer@v0.0.0-20180901003855-c20040233aed/check/check.go:143 +0x2d8\ngithub.com/golangci/golangci-lint/pkg/golinters.runInterfacer(0xc07416e0d0)\n\tgithub.com/golangci/golangci-lint/pkg/golinters/interfacer.go:63 +0x408\ngithub.com/golangci/golangci-lint/pkg/golinters.NewInterfacer.func1(0x1043920?)\n\tgithub.com/golangci/golangci-lint/pkg/golinters/interfacer.go:26 +0x29\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyze(0xc007833860)\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:190 +0xa02\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe.func2()\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:112 +0x17\ngithub.com/golangci/golangci-lint/pkg/timeutils.(*Stopwatch).TrackStage(0xc001d0e6e0, {0x11c6e5e, 0xa}, 0xc003ef6f48)\n\tgithub.com/golangci/golangci-lint/pkg/timeutils/stopwatch.go:111 +0x44\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*action).analyzeSafe(0xc003499d40?)\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_action.go:111 +0x7a\ngithub.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze.func2(0xc007833860)\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:80 +0xa8\ncreated by github.com/golangci/golangci-lint/pkg/golinters/goanalysis.(*loadingPackage).analyze in goroutine 5382\n\tgithub.com/golangci/golangci-lint/pkg/golinters/goanalysis/runner_loadingpackage.go:75 +0x205
```

**Comment by CarlJi** [comment]
seems caused by https://github.com/golangci/golangci-lint/issues/4482

**Comment by CarlJi** [comment]
related #151
